version: '3.8'

services:
  test:
    build:
      dockerfile: Dockerfile.test
      context: .
      args:
        - 'HTTP_PROXY'
        - 'HTTPS_PROXY'
    depends_on:
      - store
    command: test

  store:
    image: 'blackglory/store:0.5.0'
